### ISSUE TITLE
Imrove main page with navbar and a footer to attract more contributors for the project

### ISSUE THREAD

**Issue by ratishjain12** [ayushi-ras/JS-Game#9]
@ayushi-ras I want to improve the look and feel of the website currently it contains only the game.

Thinking of adding a footer leading to this repo or some thing do assigne me this if you want to do it :)

**Comment by iamshobhraj** [comment]
hey, can you assign this to me. I have worked navbar using tailwind css. I am a newbie in open source contribution but have experience in tailwind css and react js

**Comment by ratishjain12** [comment]
@ayushi-ras do have any kind of logo for the website?

**Comment by ratishjain12** [comment]
Ik but some sort of logo would be nice for navbar nevermind I'll simply use texf

**Comment by ayushi-ras** [comment]
@ratishjain12 yeah go ahead
